apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
  namespace: laravel
type: Opaque

#echo -n "laravel" | base64
# echo -n "secret" | base64
# bGFyYXZlbA==
# c2VjcmV0
data:
  db-database: bGFyYXZlbA==
  db-username: bGFyYXZlbA==
  db-password: c2VjcmV0