apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  db-database: {{ .Values.db.name | b64enc }}
  db-username: {{ .Values.db.username | b64enc }}
  db-password: {{ .Values.db.password | b64enc }}