apiVersion: v1  
kind: Secret
metadata:
  name: laravel-secrets
  namespace: laravel
type: Opaque   #generic secret

data:
  db-database: bGFyYXZlbA==
  db-username: bGFyYXZlbA==
  db-password: c2VjcmV0